Algoritmo "circunferencia de um triangulo"

Var
area, base, altura: real


Inicio

escreval ("a circunferencia da area de um triângulo:")
escreval()
///////////////////////////////////////////////////////////
escreval("Digite o valor da altura em metros: ")
  leia (altura)
escreval("Digite o valor da base: ")
  leia(base)
///////////////////////////////////////////////////////////
area <- (base*altura)/2

escreval("O valor da area do triângulo é: ", area)


Fimalgoritmo