Algoritmo "média da prova"

Var
PROVA1, PROVA2, PROVA3: REAL
media: REAL


Inicio
ESCREVA ("DIGITE A NOTA DA PROVA 1: ")
LEIA (PROVA1)
ESCREVAL()
ESCREVA ("DIGITE A NOTA DA PROVA 2: ")
LEIA (PROVA2)
ESCREVAL()
ESCREVA ("DIGITE A NOTA DA PROVA 3: ")
LEIA (PROVA3)
ESCREVAL()

ESCREVA("==================================================")
ESCREVAL()
     media <- (PROVA1+PROVA2+PROVA3)/3
     ESCREVA ("SUA MÉDIA NESTA DISCIPLINA É: ", media)


Fimalgoritmo