Algoritmo "sequencia"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Silvia
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Caio Lyncoln
// Data atual  : 11/08/2020
Var
// Seção de Declarações das variáveis 
u1, prox: real

Inicio

u1<-1
prox<- 1
 
 enquanto (prox<=20) faca
 escreval (u1, "/", prox)
 prox<- prox + 1
 fimenquanto
Fimalgoritmo