Algoritmo "mil vezes PROA 4.0"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Silvia
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Caio Lyncoln
// Data atual  : 10/08/2020
Var
// Seção de Declarações das variáveis 
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("COMANDO DE REPETIÇÃO")

 escreval ()
 
para contador de 1 até 1000 faca
 escrevaL ("PROA 4.0")
fimpara


Fimalgoritmo