Algoritmo "os múltiplos positivos de 7, inferiores a 1000"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Silvia
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Caio Lyncoln
// Data atual  : 13/08/2020
Var
// Seção de Declarações das variáveis 
numeros: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para numeros de 0 ate 1000 passo 7 faca
 escreval (" numero:", numeros)
fimpara

Fimalgoritmo