Algoritmo "soma de vetores"

Var
// Seção de Declarações das variáveis 
vet1: vetor[1..5] de inteiro
vet2: vetor[1..5] de inteiro
vet3: vetor[1..5] de inteiro
contador: inteiro


Inicio
para contador de 1 ate 5 faca
escreva ("digite o 1º numero: ")
leia (vet1[contador])
escreva ("digite o 2º numero: ")
leia (vet2[contador])

vet3[contador] <- vet1[contador]+ vet2[contador]
fimpara





Fimalgoritmo